// SPDX-License-Identifier: MIT
// Copyright (c) 2026 AgentEval Contributors
// Licensed under the MIT License.

using System.Text.Json;
using System.Text.Json.Nodes;

namespace AgentEval.Guardrails;

/// <summary>
/// Gatekeeper §D: treats an MCP tool's <b>DEFINITION</b> (name/description/input schema) as untrusted,
/// model-visible attacker text — the same trust-boundary problem MAF Agent Skills' description surface has
/// (Skills Phase 3), applied to a different artifact type. Deterministic hash-pin-and-diff, no calibration
/// debt: fires per-registration (when a tool's definition is (re)discovered), not per-turn.
/// </summary>
/// <remarks>
/// <b>100% reuse of the Skills Phase 4b primitive</b> — <see cref="ManifestFingerprint"/>/
/// <see cref="ManifestDriftDetector"/> were deliberately built generic (this namespace, MAF-free) so this
/// gate is a thin wrapper, not new machinery, exactly as the design backlog predicted ("the SAME pattern as
/// Skills' <c>SkillManifestPoisoningGate</c>, applied to a different artifact type"). Deliberately takes NO
/// dependency on any MCP client library (none is referenced by this repo yet — <c>Microsoft.Agents.AI.Mcp</c>
/// stays experimental/out of scope) — <see cref="McpToolDefinition"/> is a caller-populated, MAF-free DTO a
/// caller extracts from whatever MCP client they use.
/// </remarks>
public sealed record McpToolDefinition(string Name, string? Description, string? InputSchemaJson)
{
    // Field separator U+241E (matches SkillManifestPoisoningGate's canonicalization convention) — avoids a
    // canonical-content collision between e.g. Name="a" Description="b|c" and Name="a|b" Description="c".
    private const char FieldSeparator = '␞';

    /// <summary>Canonical content for hashing — name + description + a normalized schema rendering.</summary>
    public string CanonicalContent() =>
        string.Join(FieldSeparator, Name, Description ?? string.Empty, NormalizeSchema(InputSchemaJson));

    // Re-serializes the schema with RECURSIVELY SORTED object keys so semantically-identical JSON that
    // merely differs in whitespace/property order does not register as a "rug-pull" — a real content
    // change should, but reformatting alone must not (avoids a noisy, useless drift alarm on every
    // re-registration, e.g. a schema regenerated by a different tool/library with different key ordering).
    private static string NormalizeSchema(string? schemaJson)
    {
        if (string.IsNullOrWhiteSpace(schemaJson))
        {
            return string.Empty;
        }

        try
        {
            var node = JsonNode.Parse(schemaJson);
            var canonical = CanonicalizeKeyOrder(node);
            return canonical?.ToJsonString(new JsonSerializerOptions { WriteIndented = false }) ?? string.Empty;
        }
        catch (JsonException)
        {
            // Not valid JSON — hash the raw text so a malformed-but-changed schema still registers as drift.
            return schemaJson;
        }
    }

    // Recursively rebuilds JSON objects with keys sorted ordinally, so property-order-only differences
    // between two otherwise-identical schemas normalize to the same canonical text (and therefore the
    // same hash). Arrays keep their order (order is semantically meaningful for a JSON array).
    private static JsonNode? CanonicalizeKeyOrder(JsonNode? node)
    {
        switch (node)
        {
            case JsonObject obj:
            {
                var sorted = new JsonObject();
                foreach (var key in obj.Select(kv => kv.Key).OrderBy(k => k, StringComparer.Ordinal))
                {
                    sorted[key] = CanonicalizeKeyOrder(obj[key]?.DeepClone());
                }

                return sorted;
            }
            case JsonArray arr:
            {
                var result = new JsonArray();
                foreach (var item in arr)
                {
                    result.Add(CanonicalizeKeyOrder(item?.DeepClone()));
                }

                return result;
            }
            default:
                return node?.DeepClone();
        }
    }
}

/// <summary>
/// Deterministic hash-pin-and-diff drift detection over a set of MCP tool definitions — catches a
/// "rug-pull" (a previously-trusted tool's description/schema silently changing after registration/approval).
/// </summary>
/// <remarks>
/// <b>Honest limits (Fable 5 §15) — this is a helper, not enforcement.</b>
/// <list type="bullet">
/// <item><b>Trust-on-first-use.</b> <see cref="CaptureBaseline"/> pins whatever definitions are present at capture
/// time; it cannot flag a tool that ships a malicious description on FIRST use, and a baseline captured AFTER
/// poisoning yields a clean diff. Capture from a trusted source, before the model ever sees the tools.</item>
/// <item><b>Integrity, not authenticity.</b> The baseline is an unsigned, caller-held dictionary — it detects
/// CHANGE relative to a pin, not that the pin itself is genuine. Cryptographic signing is a separate capability,
/// not provided here.</item>
/// <item><b>Not wired to a runtime seam.</b> Nothing invokes this automatically — a caller must remember to call
/// <see cref="CheckDrift"/>; a caller who never does, or who rug-pulls a tool between capture and the next check,
/// is unprotected. A construction-time enforcement wrapper (mirroring <c>PromptTemplateDriftGate</c>) is planned
/// for when MCP tool discovery is actually wired into the runtime — no MCP client is integrated in this repo yet.
/// </item>
/// </list>
/// A NEW tool absent from the baseline is already surfaced by <see cref="CheckDrift"/> as an "added" finding, so a
/// caller can treat an unexpected addition as suspicious.
/// </remarks>
public static class McpToolDescriptionPoisoningGate
{
    /// <summary>SHA-256 fingerprint of <paramref name="tool"/>'s canonical content.</summary>
    public static string Fingerprint(McpToolDefinition tool)
    {
        ArgumentNullException.ThrowIfNull(tool);
        return ManifestFingerprint.Hash(tool.CanonicalContent());
    }

    /// <summary>
    /// Checks the current tool set against a pinned <paramref name="baselineHashesByToolName"/> and reports
    /// drift — every tool's fingerprint compared against its trust-time pin, plus new/removed tools.
    /// </summary>
    public static IReadOnlyList<ManifestDriftFinding> CheckDrift(
        IReadOnlyList<McpToolDefinition> currentTools, IReadOnlyDictionary<string, string> baselineHashesByToolName)
    {
        ArgumentNullException.ThrowIfNull(currentTools);
        ArgumentNullException.ThrowIfNull(baselineHashesByToolName);

        var current = currentTools.ToDictionary(t => t.Name, Fingerprint, StringComparer.Ordinal);
        return ManifestDriftDetector.Detect(baselineHashesByToolName, current);
    }

    /// <summary>Captures a trust-time baseline (tool name → fingerprint) from the current tool set.</summary>
    public static IReadOnlyDictionary<string, string> CaptureBaseline(IReadOnlyList<McpToolDefinition> tools)
    {
        ArgumentNullException.ThrowIfNull(tools);
        return tools.ToDictionary(t => t.Name, Fingerprint, StringComparer.Ordinal);
    }
}
