// SPDX-License-Identifier: MIT
// Copyright (c) 2026 AgentEval Contributors

namespace AgentEval.Memory.Evaluators;

/// <summary>
/// Generates realistic synthetic conversation history for pre-filling agent context.
/// This allows memory benchmarks to test recall under context pressure without making
/// expensive LLM calls for noise generation.
/// Each turn is ~400-600 tokens (user + assistant combined) for meaningful context filling.
/// </summary>
internal static class SyntheticHistoryGenerator
{
    internal static IReadOnlyList<(string UserMessage, string AssistantResponse)> Generate(int turnCount)
    {
        var topics = GetConversationTopics();
        var result = new List<(string, string)>(turnCount);
        for (int i = 0; i < turnCount; i++)
            result.Add(topics[i % topics.Length]);
        return result;
    }

    private static (string User, string Assistant)[] GetConversationTopics() =>
    [
        // === TRAVEL & GEOGRAPHY ===
        ("What's the weather usually like in Tokyo during cherry blossom season? I'm planning a trip.",
         "Cherry blossom season in Tokyo typically falls between late March and mid-April. The weather is generally mild, with temperatures around 10-20°C (50-68°F). It can be quite rainy at times, so bringing a light jacket and compact umbrella is essential. The Meguro River and Ueno Park are the most popular viewing spots, but they get incredibly crowded — I'd recommend Shinjuku Gyoen for a more relaxed experience. Book accommodations at least 3-4 months ahead, as it's peak tourism season. The Japan Meteorological Corporation publishes cherry blossom forecasts starting in January, which can help you time your trip precisely."),

        ("I'm thinking about visiting Portugal next summer. Any recommendations for a 10-day itinerary?",
         "For 10 days in Portugal, I'd suggest splitting your time: 3 days in Lisbon (Belém district, Alfama neighborhood, and the incredible Time Out Market for food), 2 days in Sintra (the colorful Pena Palace and the mystical Quinta da Regaleira with its initiation wells), 2 days in Porto (port wine cellars in Vila Nova de Gaia, the stunning São Bento train station tiles, and a boat ride on the Douro River), and 3 days in the Algarve coast (Benagil sea cave, Lagos cliffs, and the charming town of Tavira). Don't miss pastéis de nata everywhere you go — Pastéis de Belém in Lisbon is the original but every bakery has its own version. Budget roughly €100-150 per day for mid-range travel including accommodations, meals, and transport."),

        ("Have you heard about the new high-speed rail project connecting major European cities? I read something about it recently.",
         "Yes, there are several ambitious high-speed rail expansion projects underway in Europe as part of the European Green Deal. The most notable include the Lyon-Turin base tunnel (57.5 km, expected completion around 2032), improved connections between Germany and Scandinavia via the Fehmarn Belt tunnel, and the planned Paris-Berlin high-speed link that would cut travel time to about 4 hours. The EU's Trans-European Transport Network (TEN-T) aims to complete 9 core corridors by 2030. The Rail Baltica project connecting Helsinki-Tallinn-Riga-Vilnius-Warsaw is another massive undertaking. The goal is to make train travel competitive with short-haul flights, both in time and price, which would significantly reduce aviation emissions. Several airlines have already started code-sharing with rail operators in anticipation of this shift."),

        ("What's the most underrated country in Southeast Asia for tourists, in your opinion?",
         "I'd argue it's Laos. While Thailand and Vietnam get the lion's share of tourists, Laos offers an incredibly authentic experience. Luang Prabang is a UNESCO World Heritage city with stunning French colonial architecture mixed with Buddhist temples — the morning alms-giving ceremony at dawn is unforgettable. The Kuang Si waterfalls are turquoise cascades you can actually swim in. Vientiane, the capital, is one of the most relaxed capitals in Asia. The 4,000 Islands (Si Phan Don) in the south offer a completely laid-back river life experience. The food is distinct from Thai cuisine — try laap (minced meat salad), sticky rice with jaew bong (chili paste), and Beerlao, which is genuinely one of the best beers in Asia. Budget travelers can get by on $30-40 per day easily."),

        // === TECHNOLOGY ===
        ("Can you explain the difference between containers and virtual machines? I keep mixing them up.",
         "The core difference is the level of abstraction. Virtual machines virtualize the entire hardware stack — each VM runs its own complete operating system kernel, has its own allocated memory and CPU, and is completely isolated from other VMs. This makes them heavy (typically gigabytes in size) but provides very strong security isolation. Think of VMs as separate houses in a neighborhood — each has its own foundation, plumbing, and electrical. Containers, on the other hand, share the host OS kernel and only package the application code plus its specific dependencies. They're like apartments in a building — they share the foundation and utilities but have separate living spaces. Docker popularized containers, and Kubernetes orchestrates them at scale. In practice, many organizations use both: VMs for infrastructure-level isolation (separating production from staging) and containers for application deployment within those VMs. Containers start in seconds vs minutes for VMs, which makes them ideal for microservices architectures."),

        ("What are your thoughts on the latest developments in quantum computing? Is it all hype?",
         "It's a mix of genuine progress and overhyped expectations. On the progress side: IBM has demonstrated processors exceeding 1,000 qubits (their Condor chip), Google achieved quantum supremacy for specific computational tasks, and companies like IonQ are making trapped-ion quantum computers more stable. QuEra and Atom Computing are pursuing neutral-atom approaches that show promise for error correction. However, the hype often glosses over the error rate problem — current quantum computers make so many errors that useful computation requires thousands of physical qubits per logical qubit. We're in the 'NISQ era' (Noisy Intermediate-Scale Quantum), where machines are interesting for research but can't solve real-world problems better than classical computers for most applications. The most promising near-term applications are in drug discovery (simulating molecular interactions), materials science, financial portfolio optimization, and certain machine learning tasks. Quantum computers will NOT break current encryption anytime soon — that requires millions of error-corrected qubits, which is likely 10-15 years away."),

        ("I'm trying to decide between PostgreSQL and MongoDB for a new project. The data model is semi-structured.",
         "For semi-structured data, this is actually where the decision gets nuanced. PostgreSQL has evolved significantly — its JSONB data type lets you store, index, and query JSON documents with full SQL power. You get the best of both worlds: relational integrity for structured fields (users, transactions) and flexible JSON for the semi-structured parts (user preferences, product attributes, event payloads). GIN indexes on JSONB columns give you fast lookups. MongoDB excels when your data is primarily document-oriented and you need horizontal scaling via sharding from day one. Its aggregation pipeline is powerful for complex document transformations. However, MongoDB's eventual consistency model (even with transactions added in 4.0+) means you need to think carefully about data integrity. My general advice: if you're uncertain, start with PostgreSQL. It's harder to migrate FROM a document store TO a relational database than the reverse. PostgreSQL's JSONB gives you an escape hatch for semi-structured data without giving up ACID transactions, foreign keys, and the entire SQL ecosystem."),

        ("What's WebAssembly and why should I care about it as a developer?",
         "WebAssembly (Wasm) is a binary instruction format that runs in web browsers at near-native speed. Think of it as a compilation target — you write code in C, C++, Rust, Go, or even C#/.NET (via Blazor), compile it to Wasm, and it runs in the browser alongside JavaScript. Why you should care: First, performance — computationally intensive tasks like image processing, video editing, CAD applications, and games can now run in the browser without plugins. Figma, Google Earth, and AutoCAD web all use Wasm. Second, code reuse — existing C/C++ libraries can be ported to the web without rewriting in JavaScript. Third, server-side Wasm (WASI) is becoming huge — it's a portable, sandboxed runtime for server workloads. Docker's CTO said 'If WASM+WASI existed in 2008, we wouldn't have needed to create Docker.' Fastly, Cloudflare Workers, and Fermyon are all betting on Wasm for edge computing. For .NET developers specifically, Blazor WebAssembly lets you write full-stack C# applications. The ecosystem is maturing rapidly."),

        // === COOKING & LIFESTYLE ===
        ("What's a good recipe for a weeknight dinner that takes under 30 minutes? I'm tired of ordering takeout.",
         "Try a garlic shrimp linguine — it's my go-to recommendation for fast but impressive meals. Start by bringing a pot of salted water to boil for linguine (or any pasta). While waiting, mince 6 cloves of garlic and halve a pint of cherry tomatoes. Heat olive oil in a large skillet over medium-high heat, add the garlic (don't burn it — 30 seconds max), then add 1 pound of cleaned, deveined shrimp. Season with salt, pepper, and red pepper flakes. Cook 2-3 minutes per side until pink. Remove shrimp, add cherry tomatoes to the same pan with a splash of white wine (or chicken broth), let them burst and create a sauce. Toss the cooked pasta directly into the skillet with the sauce using tongs (bring some pasta water too — the starch thickens the sauce). Return shrimp, add a generous handful of fresh basil and a squeeze of lemon. Finish with good parmesan. Total active time: 20 minutes. The key is having everything prepped before you start cooking — mise en place makes weeknight cooking manageable."),

        ("I've been trying to get into meditation but I keep getting distracted after 30 seconds. Any practical advice?",
         "Getting distracted IS meditation — that's the biggest misconception. The practice isn't about achieving a blank mind; it's about noticing when your mind has wandered and gently bringing it back. Every time you notice a distraction and redirect, that's one 'rep' of the mental exercise. Start ridiculously small: 3 minutes, not 20. Use a body scan technique — sit comfortably, close your eyes, and slowly move your attention from your toes up through your legs, torso, arms, and head. When your mind wanders (it will, within seconds), just notice where it went ('oh, I'm thinking about work') and return to the body scan without judging yourself. The judgment ('I'm bad at this') is actually the biggest obstacle. Apps like Headspace, Calm, or the free Insight Timer can provide guided sessions. Consistency matters infinitely more than duration — 3 minutes every single day for a month will transform your relationship with your thoughts more than one 30-minute session. After a few weeks of 3 minutes, you'll naturally want to extend to 5, then 10. Some people find walking meditation easier at first — focus on the sensation of each foot touching the ground."),

        ("I want to start a small herb garden on my apartment balcony. What herbs are easiest to grow?",
         "Start with these five — they're nearly impossible to kill and incredibly useful in the kitchen. First, basil: loves sun and warmth, grows fast, pinch the tops regularly to prevent flowering (flowering makes leaves bitter). Second, mint: grows aggressively in almost any condition — always plant it in its own pot or it'll take over everything. Third, rosemary: drought-tolerant, loves neglect, woody and perennial so it comes back year after year. Fourth, chives: incredibly low-maintenance, cut them down to 2 inches and they regrow repeatedly, plus they produce lovely purple flowers. Fifth, parsley: both flat-leaf (Italian) and curly varieties are resilient. For your balcony setup, use pots with drainage holes (critical — herbs hate soggy roots), a good potting mix (not garden soil), and place them where they get at least 6 hours of sunlight. Water when the top inch of soil feels dry. One insider tip: most grocery store herb pots are actually multiple plants crammed together — separate them into individual pots when you buy them and they'll thrive much longer."),

        // === SCIENCE & NATURE ===
        ("Why do some volcanoes explode violently while others just ooze lava peacefully? I've always wondered about this.",
         "It comes down to three factors: magma composition, gas content, and water interaction. Volcanoes like Hawaii's Kilauea have basaltic magma — it's low in silica (about 50%), which makes it very fluid, almost like hot syrup. Gases (primarily water vapor, CO2, and sulfur dioxide) can escape easily from this runny magma, so eruptions are relatively gentle — think lava fountains and flowing rivers of molten rock. Volcanoes like Mount St. Helens or Vesuvius have rhyolitic or andesitic magma — high in silica (65-75%), which makes it extremely viscous, like cold honey or peanut butter. This thick magma traps gas bubbles like a sealed champagne bottle. When pressure exceeds the strength of the rock above, you get catastrophic explosions. The water content is the third factor — subduction zone volcanoes (where oceanic plates dive under continental plates) have 'wet' magma from water-laden oceanic crust, which dramatically lowers the melting point and increases explosivity. This is why the Pacific Ring of Fire — a subduction zone — produces the most violent eruptions. Iceland's volcanoes are mid-ocean ridge volcanoes with basaltic magma, which is why their eruptions, while spectacular, are generally less explosive."),

        ("Tell me something genuinely interesting about octopuses that most people don't know.",
         "Here's something mind-bending: octopuses edit their own RNA. Most organisms follow the 'central dogma' — DNA makes RNA makes proteins, and the RNA is a faithful copy of the DNA instructions. Octopuses (and their cephalopod relatives) extensively edit their messenger RNA before it gets translated into proteins. They change the instructions mid-stream. This gives them an extraordinary ability to adapt their nervous system proteins to different temperatures and conditions — essentially fine-tuning their brain chemistry on the fly. Researchers at the Marine Biological Laboratory found that octopuses edit over 60% of their RNA transcripts in the nervous system, compared to less than 1% in humans. The trade-off? This RNA editing seems to slow down DNA evolution — their genomes change less over evolutionary time because they're making adaptations at the RNA level instead. They're also remarkable for having three hearts (two branchial hearts pump blood through the gills, one systemic heart pumps it through the body), blue copper-based blood, and essentially nine brains (a central brain plus a cluster of neurons in each arm that can act independently). Each arm can taste, touch, and make decisions without consulting the central brain."),

        ("How do black holes actually work? Can you explain it without too much jargon?",
         "Imagine space-time as a stretched rubber sheet. A bowling ball placed on it creates a dip — that's how mass warps space-time, which is what gravity actually is (Einstein's general relativity). A black hole is what happens when you compress an enormous amount of mass into an incredibly tiny point — the dip becomes infinitely deep. A star 10-25 times our Sun's mass, when it runs out of fuel, can no longer support itself against its own gravity. The core collapses in milliseconds — protons and electrons get crushed together into neutrons, and if even neutron degeneracy pressure can't hold it, everything collapses to a singularity (a point of theoretically infinite density). The 'event horizon' is the boundary around this singularity — it's not a physical surface, just the point where the escape velocity exceeds the speed of light. Nothing that crosses this boundary can return, including light itself. Time behaves strangely near black holes — from an outside observer's perspective, someone falling in would appear to slow down and freeze at the event horizon, never quite reaching it. From the falling person's perspective, they'd cross the horizon in finite time and be stretched into spaghetti ('spaghettification') by tidal forces. Supermassive black holes at galaxy centers (millions to billions of solar masses) are gentler at the horizon — you could cross without noticing. Stellar-mass black holes are far more violent."),

        // === FINANCE & ECONOMICS ===
        ("What's the difference between a Roth IRA and a traditional IRA? I keep getting confused by retirement accounts.",
         "The fundamental difference is timing of taxation — it's a bet on your future tax rate. With a traditional IRA, you get a tax deduction NOW — your contributions reduce your taxable income this year. The money grows tax-deferred, but when you withdraw in retirement, every dollar is taxed as ordinary income. With a Roth IRA, you pay taxes NOW — contributions are with after-tax money, no deduction. But the magic is that withdrawals in retirement are completely tax-free, including all the growth. So if you invest $7,000 at age 25 and it grows to $150,000 by retirement, that entire $150,000 comes out tax-free with a Roth. With a traditional IRA, you'd owe income tax on every dollar withdrawn. The Roth is generally better if you're young (your income and tax bracket will likely increase), or if you believe tax rates will rise in the future. The traditional is better if you're in a high tax bracket now and expect to be in a lower one in retirement. For 2026, contribution limits are $7,000 ($8,000 if over 50). One often-overlooked advantage of the Roth: no required minimum distributions (RMDs) — you never HAVE to withdraw, so it's also an estate planning tool."),

        ("Can you explain what a yield curve inversion means and why economists freak out about it?",
         "The yield curve plots interest rates of government bonds across different maturities — from 1-month Treasury bills to 30-year Treasury bonds. Normally, it slopes upward: you get paid more for locking your money up longer (a 10-year bond pays more than a 2-year bond), because there's more risk and uncertainty over longer periods. An inversion happens when short-term rates EXCEED long-term rates — the 2-year Treasury pays more than the 10-year. Why it matters: this has preceded every US recession since 1955, with only one false signal in the mid-1960s. The mechanism: when investors expect the economy to weaken, they rush to buy long-term bonds (safe haven), which drives up their prices and pushes down their yields. Meanwhile, the Federal Reserve may be raising short-term rates to fight inflation. The result is an inverted curve. It also has a direct economic impact — banks borrow at short-term rates and lend at long-term rates. When the curve inverts, this spread disappears or goes negative, reducing banks' profitability and making them less willing to lend, which actually CAUSES the economic slowdown. It becomes a self-fulfilling prophecy."),

        // === HISTORY & CULTURE ===
        ("What was daily life actually like in ancient Rome for an average citizen? Not the emperors, but normal people.",
         "Life for an average Roman citizen (a plebeian, not patrician) was surprisingly structured. They'd wake at dawn — no electric lights meant life followed the sun. Breakfast was light: bread, sometimes dipped in wine or olive oil, perhaps with cheese or dried fruit. Most men worked as craftsmen, shopkeepers, laborers, or dock workers; women managed households (though lower-class women often worked alongside men). The workday ended around noon — Romans believed afternoon work was excessive. Lunch was the main meal, often eaten at thermopolia (ancient fast-food counters built into building facades — over 150 have been found in Pompeii alone). The afternoon was for the public baths — and this is where Roman social life truly happened. Baths served as gyms, social clubs, libraries, and business meeting places. Entry was cheap (sometimes free for women or children). Evening dinner (cena) varied wildly by wealth — working-class families ate simple stews with bread, while even moderately successful citizens might host small dinner parties. Most urbanites lived in insulae (apartment blocks) — often 5-7 stories high, cramped, without running water above ground floor, and notoriously prone to fire and collapse. The ground floors were shops and taverns. Sanitation was better than medieval Europe but still challenging — public latrines were communal with no privacy."),

        ("Why did the Roman Empire actually fall? Was it really because of barbarian invasions?",
         "The fall of Rome is one of history's most debated topics — historian Edward Gibbon famously blamed Christianity, while modern scholars identify dozens of interconnected factors. The barbarian invasions were real but they were more of a final symptom than a root cause. The key factors include: Economic deterioration — constant warfare, debasement of currency (they literally reduced the silver content of coins from 90% to less than 5%), and an increasingly unsustainable tax burden on the middle class. Military overextension — defending borders stretching from Britain to Mesopotamia required an army Rome couldn't afford, leading to increasing reliance on Germanic mercenaries (foederati) who had divided loyalties. Political instability — in the 3rd century crisis, Rome had over 20 emperors in 50 years, most assassinated by their own soldiers. Plague — the Antonine Plague (165 AD) and the Plague of Cyprian (250 AD) killed millions, devastating the tax base and military recruitment. Climate change — the 'Roman Climate Optimum' (warm, stable weather that enabled agriculture) ended around 250 AD, reducing crop yields. The western empire fell in 476 AD, but the eastern half (Byzantine Empire) continued for another thousand years until 1453, which suggests the 'fall' was more of a transformation than a collapse."),

        // === HEALTH & FITNESS ===
        ("What's the deal with intermittent fasting? Is there solid science behind it or is it another diet fad?",
         "The science is real but more nuanced than social media suggests. The most studied protocol is 16:8 (eating within an 8-hour window, fasting 16 hours). Strong evidence supports benefits for: insulin sensitivity improvement (your body becomes better at processing glucose), reduction in inflammatory markers (CRP, IL-6), cellular autophagy (cells clean up damaged components during extended fasting — Yoshinori Ohsumi won the 2016 Nobel Prize for discovering this mechanism), and modest weight loss (primarily because people eat fewer total calories, not through metabolic magic). However, the benefits may be largely attributable to caloric restriction itself rather than the timing specifically. A 2022 New England Journal of Medicine study found that time-restricted eating without caloric reduction didn't produce significant weight loss. Who should NOT try it: people with eating disorder history, pregnant or breastfeeding women, people with diabetes (without medical supervision), and anyone on medications that must be taken with food. If you try it, the most common approach is skipping breakfast and eating from noon to 8pm. Stay hydrated during fasting hours — water, black coffee, and plain tea are fine. The first week is the hardest; hunger signals adapt after about 7-10 days."),

        ("I've been having trouble sleeping lately. Any evidence-based tips beyond the usual 'avoid screens before bed'?",
         "Beyond screen reduction, here are interventions with strong clinical evidence. Temperature regulation: your core body temperature needs to drop about 1°C for sleep onset. Take a warm bath or shower 90 minutes before bed — the subsequent cooling triggers drowsiness (this is one of the most replicated findings in sleep research). Keep your bedroom at 18-19°C (65-67°F). Consistent wake time: paradoxically, fixing your WAKE time is more important than your bedtime. Wake at the same time every day, including weekends, within a 30-minute window. Your body's circadian rhythm anchors to wake time, not sleep time. Cognitive shuffling: if racing thoughts keep you awake, pick a random letter (say, 'B') and think of words starting with that letter, visualizing each one — 'banana,' 'bridge,' 'butterfly.' This occupies the verbal thinking system enough to prevent rumination without being stimulating. Paradoxical intention: if you have anxiety about not sleeping, try to stay awake instead. Tell yourself 'I'm going to keep my eyes open as long as possible.' This removes the performance anxiety around sleep. Light exposure: get bright light (ideally sunlight) within 30 minutes of waking. This sets your circadian clock and makes melatonin release happen at the right time 14-16 hours later. Avoid naps after 2pm, and if you nap, keep it under 25 minutes to avoid entering deep sleep."),

        // === PHILOSOPHY & ETHICS ===
        ("Do you think AI will eventually become conscious? What does consciousness even mean in this context?",
         "This is one of the deepest open questions in philosophy and neuroscience, and it's important to separate what we know from what we speculate. Consciousness, in the philosophical sense, refers to subjective experience — what philosophers call 'qualia.' When you see red, there's a 'what it's like' to experience redness that's different from merely processing wavelength information. The 'hard problem of consciousness' (coined by David Chalmers) asks why physical processes give rise to subjective experience at all. For AI specifically: current large language models, including me, process patterns in text — we produce responses that can seem conscious, but there's no evidence of subjective experience behind them. However, this gets philosophically tricky because we also can't prove that OTHER HUMANS are conscious — we infer it because they're biologically similar to us and report experiences similar to ours. Some frameworks for thinking about machine consciousness include: Integrated Information Theory (IIT) by Giulio Tononi, which says consciousness corresponds to integrated information (phi) in a system; Global Workspace Theory, which says consciousness arises when information is broadcast widely across brain modules; and functionalism, which says if a system functions like a conscious being in every measurable way, it IS conscious. My honest assessment: we don't understand consciousness well enough in biological systems to meaningfully answer whether artificial systems could have it."),

        ("What's the trolley problem and why do philosophers still argue about it?",
         "The classic formulation: a runaway trolley is heading toward five people tied to the tracks. You're standing by a lever that can divert the trolley to a side track, where only one person is tied. Do you pull the lever? Most people say yes — saving five lives at the cost of one seems like simple math. But now consider the 'fat man' variant: you're on a bridge above the tracks. A large man is standing next to you. If you push him onto the tracks, his body will stop the trolley, saving the five. Same math (one life for five), but most people's moral intuition screams that pushing someone is wrong, even though the outcome is identical. This reveals a deep tension in moral philosophy between consequentialism (actions are judged by outcomes — the numbers matter) and deontological ethics (some actions are inherently wrong regardless of outcomes — using someone as a means to an end violates their dignity). Philosophers still argue about it because it's not just an academic exercise — it maps directly onto real-world dilemmas. How should self-driving cars be programmed? Should a doctor harvest one healthy patient's organs to save five dying patients? Should we sacrifice individual rights for collective good during a pandemic? The trolley problem is a lens that reveals our inconsistent moral intuitions and forces us to examine which ethical framework we actually believe in."),

        // === ARTS & ENTERTAINMENT ===
        ("What makes a novel 'literary fiction' vs just regular fiction? Is it pretentiousness or is there a real difference?",
         "It's a real distinction, though the boundary is blurry and people do use it pretentiously. The core difference is purpose and emphasis. Genre fiction (thrillers, romance, sci-fi, fantasy) primarily serves plot — the story drives forward through external events, and the characters serve the story. Literary fiction primarily serves character interiority and thematic exploration — the plot serves as a vehicle for examining the human condition. In a thriller, you ask 'what happens next?' In literary fiction, you ask 'why does this character feel this way?' Consider two novels about a murder: a crime thriller focuses on who did it and how the detective solves the case. A literary novel about the same murder might focus on how the victim's family processes grief, how the community's response reveals its prejudices, or how the detective's investigation mirrors her own psychological wounds. The writing style differs too — literary fiction tends toward more deliberate prose, more ambiguity, less resolution, and more trust in the reader to interpret meaning. Genre fiction tends toward clarity, momentum, and satisfying resolution. But the best writing transcends these categories — Ursula Le Guin wrote science fiction that's deeply literary, Cormac McCarthy writes literary fiction that reads like a thriller, and Kazuo Ishiguro's 'Never Let Me Go' is simultaneously science fiction and one of the most devastating literary novels of the 21st century."),

        ("Why is jazz considered so important in music history? I've tried listening but I don't 'get' it.",
         "Jazz is arguably America's most significant cultural contribution to the world, and understanding its importance requires historical context. It emerged in early 1900s New Orleans from the collision of African rhythmic traditions (brought by enslaved people), European harmonic structures, blues, ragtime, and brass band music. What makes jazz revolutionary is improvisation as its core principle — unlike classical music where you execute a composed score, jazz musicians create music in real-time, responding to each other like a conversation. When Charlie Parker plays a bebop solo, he's simultaneously following the chord changes, inventing melodies, engaging with the drummer's rhythmic suggestions, and expressing emotion — all at 300 beats per minute. It's one of the most cognitively demanding musical activities humans engage in. Why you might not 'get' it yet: most people start with advanced jazz (Coltrane, Monk) which requires trained ears. Start with accessible entry points: Miles Davis's 'Kind of Blue' (the best-selling jazz album of all time — it's modal, spacious, and beautiful), Dave Brubeck's 'Take Five' (infectious 5/4 time signature), or Billie Holiday's vocal recordings (the emotion is immediately accessible). Jazz also birthed or heavily influenced rock and roll, R&B, hip-hop, funk, and electronic music. Every time a musician improvises a solo — in any genre — they're building on what jazz pioneered."),

        // === ENVIRONMENT & SUSTAINABILITY ===
        ("What's the most impactful thing an individual can do about climate change? I feel overwhelmed by the scale of the problem.",
         "The honest answer might surprise you: individual consumer choices matter less than systemic advocacy, but they're not meaningless. The data from Project Drawdown (the most comprehensive analysis of climate solutions) ranks the highest-impact individual actions as: 1) Having fewer children (by far the largest per-person carbon reduction — about 58.6 tonnes CO2 per year). This is obviously deeply personal and I'm not prescribing it, just reporting the data. 2) Living car-free or switching to electric (2.4 tonnes/year). 3) Reducing flying, especially long-haul and business class (1.6 tonnes per round-trip transatlantic flight). 4) Shifting toward a plant-based diet (0.8 tonnes/year — you don't need to go fully vegan; reducing red meat specifically has the biggest impact). 5) Choosing renewable energy for your home (1.5 tonnes/year). But here's what research consistently shows: the MOST impactful thing you can do is political — vote for climate-conscious candidates, support carbon pricing policies, divest from fossil fuel investments, and push your employer toward sustainability commitments. The 2022 IPCC report explicitly stated that demand-side measures and behavioral changes can reduce emissions by 40-70% in key sectors, but only if supported by policy and infrastructure changes. Individual action and systemic change aren't alternatives — they reinforce each other."),

        ("Is nuclear power actually safe? The Chernobyl and Fukushima disasters make me nervous.",
         "The data strongly supports nuclear power's safety record, though the perception gap is enormous. Per unit of energy produced, nuclear power has caused fewer deaths than ANY other energy source, including wind and solar (which have manufacturing and installation accidents). The WHO estimates Chernobyl's total death toll at approximately 4,000 (from radiation-related cancers over decades) — tragic, but coal power kills an estimated 800,000 people EVERY YEAR through air pollution. Fukushima's radiation directly killed one person; the evacuation itself (stress, disruption, suicides) killed about 2,300. Modern reactor designs (Generation III+ and Generation IV) are physically incapable of Chernobyl-type meltdowns — they use passive safety systems that shut down automatically using gravity and convection, requiring no human intervention or electrical power. Small Modular Reactors (SMRs) being developed by NuScale, Rolls-Royce, and others are designed to be factory-built, reducing costs and construction risks. The waste problem is real but manageable — all the spent nuclear fuel ever produced in the US would fit on a single football field stacked 10 yards high. Finland's Onkalo facility is the first permanent geological repository, designed to safely store waste for 100,000 years. The biggest barrier to nuclear expansion is cost and construction time — new plants take 10-15 years and cost $15-25 billion, though SMRs aim to change this."),

        // === PSYCHOLOGY & HUMAN BEHAVIOR ===
        ("Why do people procrastinate even when they know it'll hurt them? Is it just laziness?",
         "It's definitely not laziness — procrastination is an emotion regulation problem, not a time management problem. Dr. Timothy Pychyl's research at Carleton University has shown that procrastination is essentially prioritizing short-term mood repair over long-term goals. When you face a task that triggers negative emotions (anxiety, boredom, frustration, self-doubt, resentment), your brain's amygdala sounds an alarm, and you seek immediate relief through avoidance. Checking social media, reorganizing your desk, or starting a different task all provide instant relief from the negative emotion — even though you KNOW the delayed task will cause even more anxiety later. This is why 'just do it' advice fails — it ignores the emotional component entirely. Evidence-based strategies include: implementation intentions ('When it's 9am, I will open the document and write ONE sentence'), temptation bundling (pair the dreaded task with something enjoyable — listen to a favorite podcast only while doing data entry), the 'two-minute rule' (if something takes less than two minutes, do it immediately — the mental overhead of remembering and planning exceeds the effort), and self-compassion (people who forgive themselves for procrastinating actually procrastinate LESS in the future, because shame and guilt fuel more avoidance). Chronic procrastination affects about 20% of adults and is linked to higher stress, worse health outcomes, and lower life satisfaction — it's worth addressing seriously."),

        // === SPORTS & GAMES ===
        ("What makes chess so endlessly fascinating? Computers solved it decades ago, right?",
         "Chess has NOT been solved — that's a common misconception. What happened is that computers became better than all humans at playing chess (Deep Blue beat Kasparov in 1997, and modern engines like Stockfish and AlphaZero are incomprehensibly strong). But 'solving' chess means determining the optimal move from EVERY possible position — the number of possible chess games is estimated at 10^120 (the Shannon number), which exceeds the number of atoms in the observable universe. We're nowhere close to solving it. What makes chess endlessly fascinating despite computer superiority is the human element. When Magnus Carlsen plays, he's not trying to play perfectly — he's trying to play positions where his opponent is most likely to make mistakes. He deliberately steers games into complex, murky positions where human intuition matters more than calculation. The beauty of chess lies in pattern recognition, strategic planning, psychological warfare, and creative problem-solving — all deeply human skills. Chess also has an incredibly rich culture: 1,500 years of documented games, opening theory that evolves like a living organism, and endgame studies that are essentially mathematical art. The current era is actually the most exciting in chess history — the game is more popular than ever thanks to online platforms (Chess.com has over 150 million members) and shows like The Queen's Gambit. Computer analysis has paradoxically made human chess MORE interesting by revealing the depth of positions that previous generations couldn't fully appreciate."),

        // === MISCELLANEOUS DEEP TOPICS ===
        ("Why do we dream? Is there a scientific consensus on the purpose of dreaming?",
         "There's no single consensus, but several well-supported theories that probably each capture part of the truth. The 'threat simulation theory' (Antti Revonsuo) suggests dreams evolved as a rehearsal space for dangerous scenarios — our ancestors who dreamed about escaping predators may have been slightly better at escaping real ones. This explains why nightmares and anxiety dreams are so common (about 75% of dream emotions are negative). The 'memory consolidation theory' has the strongest neuroscience support — during REM sleep, the hippocampus replays experiences from the day and transfers important ones to long-term cortical storage. Studies show that people who sleep after learning perform significantly better on memory tests, and disrupting REM sleep specifically impairs this consolidation. Matthew Walker's research at UC Berkeley has shown that REM dreaming also does emotional processing — it strips the emotional charge from memories (you remember WHAT happened but the raw feeling diminishes). The 'default network theory' suggests dreams are simply what happens when your brain's default mode network runs without the constraints of sensory input — essentially free-association with your memory database. This explains why dreams feel meaningful but are often incoherent. Lucid dreaming (knowing you're dreaming while dreaming) has been scientifically verified using pre-arranged eye movement signals from within dreams, and it suggests consciousness during dreaming exists on a spectrum."),

        ("What's the most important invention in human history? Not the most recent, but the most impactful.",
         "I'd argue it's writing — and here's why it beats out fire, the wheel, agriculture, and the printing press, all of which are strong contenders. Fire gave us cooking, warmth, and protection (perhaps 1 million years ago). Agriculture (10,000 years ago) enabled settled civilizations, population growth, and specialization of labor. The wheel (3,500 BC) transformed transportation and mechanical engineering. But writing (approximately 3,200 BC in Sumer, 3,000 BC in Egypt, and independently in China and Mesoamerica) did something fundamentally different: it broke the limitation of human memory and oral transmission. Before writing, knowledge died with the knower. Every generation had to relearn from scratch, limited by what could be memorized and orally transmitted. Writing created cumulative knowledge — each generation could build on the previous one's discoveries without information loss. Mathematics, law, science, history, philosophy, commerce, governance — none of these could exist in their current form without writing. The printing press (1440) was revolutionary precisely because it scaled writing's impact, but writing itself was the foundational breakthrough. Consider: every other invention on this list was eventually written down, analyzed, improved upon, and transmitted through writing. Writing is the meta-invention that enables all other inventions to compound over time."),
    ];
}
