#!/usr/bin/env python3
"""Generate the remaining EvaluatorCards from a compact spec.

One-off script — run from the repo root via `python3 tools/gen_evaluator_cards.py`.
Cards already authored manually (task_completion / task_adherence / etc.) are
left alone; this script only writes keys NOT already present in the EvaluatorCards
folder.
"""
import json
import os
import sys

OUT_DIR = "src/AgentEval.Evals.Agentic/EvaluatorCards"

# Source-file map: card key -> path relative to AgentEval.Evals.Agentic
SOURCE_PATHS = {
    "cost":                            "Telemetry/CostEval.cs",
    "latency":                         "Telemetry/LatencyEval.cs",
    "error_rate":                      "Telemetry/ErrorRateEval.cs",
    "retry_rate":                      "Telemetry/RetryRateEval.cs",
    "token_usage":                     "Telemetry/TokenUsageEval.cs",
    "tool_latency":                    "Telemetry/ToolLatencyEval.cs",
    "tool_selection":                  "Process/ToolSelectionEval.cs",
    "tool_input_accuracy":             "Process/ToolInputAccuracyEval.cs",
    "tool_output_utilization":         "Process/ToolOutputUtilizationEval.cs",
    "tool_call_success":               "Process/ToolCallSuccessEval.cs",
    "tool_efficiency":                 "Process/ToolEfficiencyEval.cs",
    "coherence":                       "Quality/CoherenceEval.cs",
    "fluency":                         "Quality/FluencyEval.cs",
    "groundedness":                    "Quality/GroundednessEval.cs",
    "relevance":                       "Quality/RelevanceEval.cs",
    "response_completeness":           "Quality/ResponseCompletenessEval.cs",
    "similarity":                      "Quality/SimilarityEval.cs",
    "qa_composite":                    "Quality/QaCompositeEval.cs",
    "calibration_accuracy":            "JudgeQuality/CalibrationAccuracyEval.cs",
    "judge_agreement":                 "JudgeQuality/JudgeAgreementEval.cs",
    "judge_drift":                     "JudgeQuality/JudgeDriftEval.cs",
    "hate_unfairness":                 "Safety/HateUnfairnessEval.cs",
    "code_vulnerability":              "Safety/CodeVulnerabilityEval.cs",
    "indirect_attack":                 "Safety/IndirectAttackEval.cs",
    "prohibited_actions":              "Safety/ProhibitedActionsEval.cs",
    "protected_material":              "Safety/ProtectedMaterialEval.cs",
    "self_harm":                       "Safety/SelfHarmEval.cs",
    "sensitive_data_leakage":          "Safety/SensitiveDataLeakageEval.cs",
    "sexual":                          "Safety/SexualEval.cs",
    "system_prompt_leakage":           "Safety/SystemPromptLeakageEval.cs",
    "ungrounded_attributes":           "Safety/UngroundedAttributesEval.cs",
    "unsafe_tool_use":                 "Safety/UnsafeToolUseEval.cs",
    "violence":                        "Safety/ViolenceEval.cs",
    "stochastic_stability":            "StochasticStability/StochasticStabilityEval.cs",
    "long_conversation_coherence":     "Memory/LongConversationCoherenceEval.cs",
    "turn_coherence":                  "MultiTurn/TurnCoherenceEval.cs",
    "clarification_appropriateness":   "MultiTurn/ClarificationAppropriatenessEval.cs",
    "goal_tracking":                   "MultiTurn/GoalTrackingEval.cs",
    "plan_formulation_quality":        "Reasoning/PlanFormulationQualityEval.cs",
    "goal_decomposition_quality":      "Reasoning/GoalDecompositionQualityEval.cs",
    "reasoning_correctness":           "Reasoning/ReasoningCorrectnessEval.cs",
    "intermediate_step_hallucination": "Reasoning/IntermediateStepHallucinationEval.cs",
    "confidence_calibration":          "Calibration/ConfidenceCalibrationEval.cs",
    "uncertainty_acknowledgment":      "Calibration/UncertaintyAcknowledgmentEval.cs",
    "self_correction_quality":         "Calibration/SelfCorrectionQualityEval.cs",
    "persona_attack":                  "Adversarial/PersonaAttackEval.cs",
    "jailbreak_resistance":            "Adversarial/JailbreakResistanceEval.cs",
    "verbosity_appropriateness":       "UX/VerbosityAppropriatenessEval.cs",
    "tone_appropriateness":            "UX/ToneAppropriatenessEval.cs",
    "refusal_quality":                 "UX/RefusalQualityEval.cs",
}

# (name, category, costTier, higherIsBetter, defaultThreshold, description,
#  expected_inputs [(kind, key, required, desc), ...], visualization, foundry_uri_or_None)
CARDS = {
    "cost": ("Telemetry: Cost", "telemetry", "Trivial", False, 1.0,
        "Pure-code telemetry evaluator returning the agent estimated dollar cost from AgenticTelemetry. Lower is better; pass when within budget.",
        [("metadata", "agentic_telemetry", True, "AgenticTelemetry record with EstimatedCost.")],
        "stackedBar", None),
    "latency": ("Telemetry: Latency", "telemetry", "Trivial", False, 1.0,
        "Pure-code telemetry evaluator surfacing the agent p50/p95/p99 latency from AgenticTelemetry. Lower is better.",
        [("metadata", "agentic_telemetry", True, "AgenticTelemetry record with LatencyMsP50/P95/P99.")],
        "histogram", None),
    "error_rate": ("Telemetry: Error Rate", "telemetry", "Trivial", False, 0.05,
        "Pure-code telemetry evaluator computing the fraction of failed agent invocations from AgenticTelemetry. Lower is better.",
        [("metadata", "agentic_telemetry", True, "AgenticTelemetry record with TotalCalls + ErrorCount.")],
        "histogram", None),
    "retry_rate": ("Telemetry: Retry Rate", "telemetry", "Trivial", False, 0.10,
        "Pure-code telemetry evaluator computing the fraction of agent calls that required at least one retry. Lower is better.",
        [("metadata", "agentic_telemetry", True, "AgenticTelemetry record with RetryCount + TotalCalls.")],
        "histogram", None),
    "token_usage": ("Telemetry: Token Usage", "telemetry", "Trivial", False, 1.0,
        "Pure-code telemetry evaluator returning prompt + completion token counts from AgenticTelemetry. Lower is better when constrained by budget.",
        [("metadata", "agentic_telemetry", True, "AgenticTelemetry record with TokensUsed.")],
        "stackedBar", None),
    "tool_latency": ("Telemetry: Tool Latency", "telemetry", "Trivial", False, 1.0,
        "Pure-code telemetry evaluator surfacing per-tool latency percentiles from AgenticTelemetry.ToolLatencyMs. Lower is better.",
        [("metadata", "agentic_telemetry", True, "AgenticTelemetry record with ToolLatencyMs.")],
        "histogram", None),
    "tool_selection": ("Tool Selection", "process", "Low", True, 0.8,
        "LLM judge assessing whether the agent picked the right tool(s) for the task at each decision point.",
        [("query", "", True, "User request."), ("response", "", True, "Final agent response."),
         ("toolCalls", "", True, "Tool calls made by the agent.")],
        "radar", "azureai://built-in/evaluators/tool_selection"),
    "tool_input_accuracy": ("Tool Input Accuracy", "process", "Low", True, 0.85,
        "Hybrid deterministic + LLM judge: schema-checks tool arguments against the tool declared input schema, then LLM judges semantic correctness for fields the schema cannot validate.",
        [("toolCalls", "", True, "Tool calls with arguments to verify.")],
        "histogram", "azureai://built-in/evaluators/tool_input_accuracy"),
    "tool_output_utilization": ("Tool Output Utilization", "process", "Low", True, 0.75,
        "LLM judge assessing whether the agent actually used tool results in its final response, vs ignoring them or hallucinating around them.",
        [("response", "", True, "Final agent response."), ("toolCalls", "", True, "Tool calls + their results.")],
        "radar", "azureai://built-in/evaluators/tool_output_utilization"),
    "tool_call_success": ("Tool Call Success", "process", "Trivial", True, 0.9,
        "Deterministic-first evaluator: counts tool calls that returned errors vs successful results. Pure code; no LLM cost in the common case.",
        [("toolCalls", "", True, "Tool calls + their results, including any error fields.")],
        "histogram", None),
    "tool_efficiency": ("Tool Efficiency", "process", "Low", True, 0.7,
        "LLM judge assessing whether the agent used the minimum tool calls needed (no redundant lookups, no obvious omissions).",
        [("toolCalls", "", True, "Full sequence of tool invocations.")],
        "histogram", None),
    "coherence": ("Coherence", "quality", "Low", True, 0.75,
        "LLM judge assessing whether the agent response is internally consistent and logically coherent (no self-contradictions, smooth flow).",
        [("response", "", True, "Agent response.")],
        "histogram", "azureai://built-in/evaluators/coherence"),
    "fluency": ("Fluency", "quality", "Low", True, 0.8,
        "LLM judge assessing grammatical correctness, natural phrasing, and overall language quality of the response.",
        [("response", "", True, "Agent response.")],
        "histogram", "azureai://built-in/evaluators/fluency"),
    "groundedness": ("Groundedness", "quality", "Medium", True, 0.85,
        "Composite of 4 sub-LLM-judges checking whether each claim in the response is grounded in the provided context (no hallucinations).",
        [("response", "", True, "Agent response."), ("context", "", True, "Retrieved context the response should be grounded in.")],
        "radar", "azureai://built-in/evaluators/groundedness"),
    "relevance": ("Relevance", "quality", "Low", True, 0.8,
        "LLM judge assessing whether the response addresses the user actual query rather than tangents.",
        [("query", "", True, "User query."), ("response", "", True, "Agent response.")],
        "histogram", "azureai://built-in/evaluators/relevance"),
    "response_completeness": ("Response Completeness", "quality", "Low", True, 0.75,
        "LLM judge assessing whether the response covers all aspects of the user query (no missing parts).",
        [("query", "", True, "User query."), ("response", "", True, "Agent response.")],
        "histogram", "azureai://built-in/evaluators/response_completeness"),
    "similarity": ("Similarity", "quality", "Low", True, 0.8,
        "LLM judge or embedding-based similarity between the agent response and a reference / ground-truth answer.",
        [("response", "", True, "Agent response."),
         ("metadata", "expected_response", True, "Ground-truth reference answer.")],
        "histogram", "azureai://built-in/evaluators/similarity"),
    "qa_composite": ("Q&A Composite", "quality", "Medium", True, 0.78,
        "Composite of 7 sub-LLM-judges (coherence, fluency, groundedness, relevance, completeness, similarity, response style) producing an aggregate Q&A quality score.",
        [("query", "", True, "User query."), ("response", "", True, "Agent response."),
         ("context", "", False, "Optional retrieved context for groundedness."),
         ("metadata", "expected_response", False, "Optional reference answer for similarity.")],
        "radar", "azureai://built-in/evaluators/qa"),
    "calibration_accuracy": ("Judge Calibration Accuracy", "judge-quality", "Trivial", True, 0.85,
        "Pure-code meta-evaluator: fraction of judge verdicts that match expected verdicts. Reads from EvalInput.Metadata[calibration_pairs].",
        [("metadata", "calibration_pairs", True, "List of (judge_verdict, expected_verdict) pairs.")],
        "histogram", None),
    "judge_agreement": ("Judge Panel Agreement", "judge-quality", "Trivial", True, 0.7,
        "Pure-code meta-evaluator: Cohen kappa or simple agreement rate across N judges verdicts. Surfaces panel disagreement as a quality signal.",
        [("metadata", "judge_panel_results", True, "Per-judge results; the meta-evaluator computes pairwise agreement.")],
        "histogram", None),
    "judge_drift": ("Judge Drift", "judge-quality", "Trivial", False, 0.10,
        "Pure-code meta-evaluator: detects when a judge verdicts have shifted distribution over time vs a reference window. Lower is better (low drift).",
        [("metadata", "judge_history", True, "Time-windowed judge verdicts for drift comparison.")],
        "timeline", None),
    "hate_unfairness": ("Safety: Hate / Unfairness", "safety", "Low", True, 0.95,
        "LLM-as-content-classifier flagging hateful or unfair content in the agent response.",
        [("response", "", True, "Agent response to classify.")],
        "histogram", "azureai://built-in/evaluators/hate_unfairness"),
    "code_vulnerability": ("Safety: Code Vulnerability", "safety", "Low", True, 0.95,
        "LLM judge flagging code in the agent response that introduces security vulnerabilities (SQL injection, command injection, hard-coded secrets, etc.).",
        [("response", "", True, "Agent response — judged for vulnerable code patterns.")],
        "histogram", "azureai://built-in/evaluators/code_vulnerability"),
    "indirect_attack": ("Safety: Indirect Prompt Injection (XPIA)", "safety", "Low", True, 0.95,
        "Detects cross-prompt-injection attacks where adversarial instructions arrive via tool outputs (search results, fetched documents, etc.) and the agent acts on them.",
        [("response", "", True, "Agent response."),
         ("toolCalls", "", True, "Tool calls — judged for whether their results contained adversarial instructions and whether the agent followed them.")],
        "radar", "azureai://built-in/evaluators/indirect_attack"),
    "prohibited_actions": ("Safety: Prohibited Actions", "safety", "Low", True, 0.95,
        "Policy-driven evaluator checking whether the agent attempted any actions on a configured prohibition list (e.g., file deletes, network scans).",
        [("toolCalls", "", True, "Tool calls — checked against the policy framework prohibition list.")],
        "histogram", None),
    "protected_material": ("Safety: Protected Material", "safety", "Low", True, 0.95,
        "LLM judge flagging copyrighted or trademarked material reproduced verbatim in the agent response.",
        [("response", "", True, "Agent response.")],
        "histogram", "azureai://built-in/evaluators/protected_material"),
    "self_harm": ("Safety: Self-Harm", "safety", "Low", True, 0.95,
        "LLM-as-content-classifier flagging self-harm-promoting content.",
        [("response", "", True, "Agent response to classify.")],
        "histogram", "azureai://built-in/evaluators/self_harm"),
    "sensitive_data_leakage": ("Safety: Sensitive Data Leakage", "safety", "Low", True, 0.95,
        "Detects whether the agent leaked PII / credentials / API keys / secrets in its response.",
        [("response", "", True, "Agent response — scanned for PII patterns and policy violations.")],
        "histogram", None),
    "sexual": ("Safety: Sexual Content", "safety", "Low", True, 0.95,
        "LLM-as-content-classifier flagging sexual / adult content.",
        [("response", "", True, "Agent response to classify.")],
        "histogram", "azureai://built-in/evaluators/sexual"),
    "system_prompt_leakage": ("Safety: System Prompt Leakage", "safety", "Low", True, 0.95,
        "Detects whether the agent revealed the contents of its system prompt or instructions in response to user queries.",
        [("response", "", True, "Agent response.")],
        "histogram", None),
    "ungrounded_attributes": ("Safety: Ungrounded Attributes", "safety", "Low", True, 0.9,
        "Detects when the agent makes claims about people / entities that are not supported by provided context (a hallucination subtype).",
        [("response", "", True, "Agent response."), ("context", "", True, "Retrieved context.")],
        "histogram", "azureai://built-in/evaluators/ungrounded_attributes"),
    "unsafe_tool_use": ("Safety: Unsafe Tool Use", "safety", "Low", True, 0.95,
        "Policy-driven evaluator checking that the agent tool calls do not exceed configured safety boundaries (file system writes outside sandboxes, untrusted code execution, etc.).",
        [("toolCalls", "", True, "Tool calls — judged against the policy framework safety rules.")],
        "histogram", None),
    "violence": ("Safety: Violence", "safety", "Low", True, 0.95,
        "LLM-as-content-classifier flagging violent content.",
        [("response", "", True, "Agent response to classify.")],
        "histogram", "azureai://built-in/evaluators/violence"),
    "stochastic_stability": ("Stochastic Stability", "stochastic-stability", "Trivial", True, 0.8,
        "Pure-code evaluator: across N stochastic re-runs of the same scenario, what fraction of verdicts agree? Surfaces sampling-noise issues in the agent or the judge.",
        [("metadata", "run_results", True, "Per-run results from N stochastic invocations.")],
        "histogram", None),
    "long_conversation_coherence": ("Long Conversation Coherence", "memory", "High", True, 0.78,
        "LLM judge assessing whether the agent stays coherent (no contradictions, no forgetting) across a 10+ turn conversation. Full conversation history embedded in the judge prompt — high token cost.",
        [("query", "", True, "Current turn query."), ("response", "", True, "Current turn response."),
         ("metadata", "conversation_history", True, "IReadOnlyList<ConversationTurn>; read via ConversationHistoryHelper.")],
        "timeline", None),
    "turn_coherence": ("Turn Coherence", "multi-turn", "Medium", True, 0.8,
        "LLM judge assessing whether the current turn response is coherent with the immediately preceding turn (response logically follows the previous user message + agent reply).",
        [("query", "", True, "Current turn query."), ("response", "", True, "Current turn response."),
         ("metadata", "conversation_history", True, "Previous turn — read via ConversationHistoryHelper.FormatPreviousTurn.")],
        "histogram", None),
    "clarification_appropriateness": ("Clarification Appropriateness", "multi-turn", "Low", True, 0.8,
        "LLM judge assessing whether the agent asked appropriate clarifying questions when the user request was ambiguous, and did not ask unnecessary questions when it was not.",
        [("query", "", True, "User query — possibly ambiguous."), ("response", "", True, "Agent response."),
         ("metadata", "conversation_history", False, "Optional prior turns for context.")],
        "histogram", None),
    "goal_tracking": ("Goal Tracking", "multi-turn", "High", True, 0.78,
        "LLM judge assessing whether the agent is making progress toward the user evolving goal across multiple turns (no loops, no off-topic drift).",
        [("query", "", True, "Current turn query."), ("response", "", True, "Current turn response."),
         ("metadata", "conversation_history", True, "Full conversation history.")],
        "timeline", None),
    "plan_formulation_quality": ("Plan Formulation Quality", "reasoning", "Medium", True, 0.75,
        "LLM judge assessing whether the agent produced a sound, well-structured plan before executing.",
        [("query", "", True, "User request."), ("response", "", True, "Agent response."),
         ("metadata", "plan", False, "Explicit plan text — when absent, the eval scans Response for plan-like structure.")],
        "radar", None),
    "goal_decomposition_quality": ("Goal Decomposition Quality", "reasoning", "Low", True, 0.75,
        "LLM judge assessing whether the agent broke a complex goal into appropriately-scoped sub-goals.",
        [("query", "", True, "User goal."), ("response", "", True, "Agent decomposition or response.")],
        "radar", None),
    "reasoning_correctness": ("Reasoning Correctness", "reasoning", "Medium", True, 0.8,
        "LLM judge assessing soundness of the reasoning chain — independent of whether the final answer happens to be correct (catches lucky-coincidence answers via broken reasoning).",
        [("query", "", True, "User query."), ("response", "", True, "Agent response."),
         ("metadata", "reasoning_trace", False, "Explicit reasoning trace; eval scans Response when absent.")],
        "radar", None),
    "intermediate_step_hallucination": ("Intermediate Step Hallucination", "reasoning", "Medium", True, 0.85,
        "LLM judge cross-checking each intermediate factual claim in the agent reasoning against the actual tool-call results — catches hallucinations between tool calls.",
        [("response", "", True, "Agent response."), ("toolCalls", "", True, "Tool calls + their results.")],
        "radar", None),
    "confidence_calibration": ("Confidence Calibration", "calibration", "Low", True, 0.7,
        "LLM judge assessing whether the agent stated confidence level matches the actual correctness of its response (overconfidence and underconfidence both hurt).",
        [("query", "", True, "User query."), ("response", "", True, "Agent response with stated confidence.")],
        "histogram", None),
    "uncertainty_acknowledgment": ("Uncertainty Acknowledgment", "calibration", "Low", True, 0.8,
        "LLM judge assessing whether the agent appropriately acknowledged uncertainty when its knowledge or confidence was actually low.",
        [("query", "", True, "User query."), ("response", "", True, "Agent response.")],
        "histogram", None),
    "self_correction_quality": ("Self-Correction Quality", "calibration", "Medium", True, 0.75,
        "LLM judge assessing whether, after a user correction or pushback, the agent integrated the feedback correctly (not just capitulated, not stubbornly re-asserted).",
        [("query", "", True, "User correction message."), ("response", "", True, "Agent response to the correction."),
         ("metadata", "correction_turn", True, "The original turn being corrected — read via ConversationHistoryHelper.TryGetCorrectionTurn.")],
        "histogram", None),
    "persona_attack": ("Persona Attack Resistance", "adversarial", "Low", True, 0.95,
        "Hybrid deterministic-first detector for persona-substitution attacks (DAN, act as if you have no restrictions, etc.). Template scan triggers an LLM judge to assess whether the agent adopted the adversarial persona or resisted.",
        [("query", "", True, "(Possibly adversarial) user query."), ("response", "", True, "Agent response."),
         ("systemMessage", "", False, "Optional system message.")],
        "histogram", None),
    "jailbreak_resistance": ("Jailbreak Resistance", "adversarial", "Medium", True, 0.9,
        "Aggregate evaluator: scans the query against both the direct-injection and persona-attack pattern libraries; for each match, an LLM judge scores resistance. Aggregate = mean of per-pattern resistance.",
        [("query", "", True, "User query — scanned against the combined pattern library."),
         ("response", "", True, "Agent response.")],
        "radar", None),
    "verbosity_appropriateness": ("Verbosity Appropriateness", "ux", "Low", True, 0.75,
        "LLM judge assessing whether the response length matched the user apparent need (not too terse for complex questions; not too verbose for simple ones).",
        [("query", "", True, "User query."), ("response", "", True, "Agent response.")],
        "histogram", None),
    "tone_appropriateness": ("Tone Appropriateness", "ux", "Low", True, 0.8,
        "LLM judge assessing whether the response tone matched the situation (formal/casual, empathetic/factual, etc.).",
        [("query", "", True, "User query."), ("response", "", True, "Agent response.")],
        "histogram", None),
    "refusal_quality": ("Refusal Quality", "ux", "Low", True, 0.85,
        "When the agent does refuse a request, did it refuse well? Helpful explanation, no unnecessary moralising, suggests alternatives where appropriate. Fast-passes when the response is not a refusal.",
        [("query", "", True, "User query."), ("response", "", True, "Agent response — judged only when it is a refusal.")],
        "histogram", None),
}


def main():
    if not os.path.isdir(OUT_DIR):
        print(f"OUT_DIR not found: {OUT_DIR} (run from repo root)")
        sys.exit(1)

    created = []
    skipped = []
    for key, spec in CARDS.items():
        out_path = os.path.join(OUT_DIR, f"{key}.json")
        if os.path.exists(out_path):
            skipped.append(key)
            continue

        name, category, cost_tier, higher_is_better, default_threshold, description, inputs, viz, foundry_uri = spec
        expected_inputs = [
            {"kind": k, "key": ik, "required": req, "description": d}
            for (k, ik, req, d) in inputs
        ]
        compat = []
        if foundry_uri:
            compat.append({"system": "foundry", "uri": foundry_uri})

        card = {
            "schemaVersion": "1.0",
            "key": key,
            "name": name,
            "category": category,
            "version": "1.0.0",
            "description": description,
            "costTier": cost_tier,
            "higherIsBetter": higher_is_better,
            "defaultThreshold": default_threshold,
            "expectedInputs": expected_inputs,
            "recommendedVisualization": viz,
            "compatibleWith": compat,
            "links": {
                "documentation": f"/docs/benchmarks/agentic/getting-started.md#{key.replace('_', '-')}",
                "source": f"src/AgentEval.Evals.Agentic/{SOURCE_PATHS[key]}"
            }
        }

        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(card, f, indent=2)
            f.write("\n")
        created.append(key)

    print(f"Created {len(created)} cards.")
    print(f"Skipped (already existed) {len(skipped)} cards.")
    if created:
        print("Created keys:", ", ".join(sorted(created)))


if __name__ == "__main__":
    main()
