// SPDX-License-Identifier: MIT
// Copyright (c) 2026 AgentEval Contributors

using AgentEval.Benchmarks;
using AgentEval.Memory.External.LongMemEval;
using AgentEval.Memory.External.Models;
using Xunit;

namespace AgentEval.Memory.Tests.DataLoading;

/// <summary>
/// Sampling composition control: selecting question types, controlling abstention, and — above all —
/// proving that a run which asks for none of it still draws exactly the sample it drew before.
/// </summary>
/// <remarks>
/// <para>
/// Runs against <c>longmemeval-sampling-fixture.json</c>: the 500 real question ids and
/// question_type values of <c>longmemeval_s_cleaned.json</c>, in the dataset's own order, with no
/// question text, answers or haystack content. Sampling reads only type, id and order, so selection
/// here is identical to selection against the real file — while the real file stays gitignored and
/// these tests still run in CI.
/// </para>
/// </remarks>
public class LongMemEvalSamplingCompositionTests
{
    private const string SingleSessionAssistant = "single-session-assistant";
    private const string TemporalReasoning = "temporal-reasoning";

    private static string FixturePath()
        => Path.Combine(AppContext.BaseDirectory, "DataLoading", "longmemeval-sampling-fixture.json");

    private static IReadOnlyList<LongMemEvalEntry> Load(ExternalBenchmarkOptions options)
        => LongMemEvalDataLoader.LoadFromFile(FixturePath(), options);

    // ── The fixture itself ────────────────────────────────────────────────────

    [Fact]
    public void Fixture_MatchesTheRealDatasetShape()
    {
        var all = Load(new ExternalBenchmarkOptions());

        Assert.Equal(500, all.Count);
        Assert.Equal(30, all.Count(e => e.IsAbstention));
        // Six question types, and abstention is orthogonal to all of them — the property that makes
        // type stratification unable to say anything about abstention coverage.
        Assert.Equal(6, all.Select(e => e.QuestionType).Distinct().Count());
        Assert.All(all.Where(e => e.IsAbstention), e => Assert.DoesNotContain("_abs", e.QuestionType));
    }

    // ── Ask 1 proof: defaults are byte-identical to v0.19.0-beta ──────────────

    /// <summary>
    /// The exact selections v0.19.0-beta produces for these configurations, generated by running the
    /// released loader (commit c470e80) against this fixture before any of the composition work
    /// existed. Sealed benchmark bases are only comparable while these stay fixed, so any change to
    /// the default sampling path fails here rather than silently re-drawing someone's baseline.
    /// </summary>
    public static TheoryData<int, bool, int, string> V019GoldenSelections() => new()
    {
        {
            50, true, 42,
            "19b5f2b3,5d3d2817,118b2229,577d4d32,94f70d80,6b168ec8,8e9d538c,9aaed6a3,d682f1a2,67e0d0f2," +
            "eeda8a6d,129d1232,1f2b8d4f,edced276,81507db6,a9f6b44c,7405e8b1,36b9f61e,09ba9854,4adc0475," +
            "6b7dfb22,32260d93,35a27287,b9cfe692,993da5e2,gpt4_68e94288,gpt4_b5700ca9,c8090214," +
            "gpt4_1e4a8aeb,gpt4_2f584639,gpt4_4edbafa2,71017276,gpt4_4ef30696,gpt4_6dc9b45b," +
            "gpt4_b0863698,bbf86515,ba61f0b9,6aeb4375,7e974930,dad224aa,06db6396,7a87bd0c,08e075c7," +
            "ce6d2d27,89527b6b,4baee567,352ab8bd,f523d9fe,58470ed2,561fabcd"
        },
        {
            50, false, 42,
            "gpt4_b4a80587,6d550036,0862e8bf_abs,gpt4_e061b84f,2e6d26dc,75832dbd,c8090214_abs," +
            "gpt4_61e13b3c,d682f1a2,08e075c7,gpt4_2f91af09,35a27287,4dfccbf7,9aaed6a3,1192316e," +
            "54026fce,gpt4_ec93e27f,8550ddae,59524333,gpt4_468eb064,09ba9854,58ef2f1c,15745da0_abs," +
            "8c18457d,eace081b,gpt4_b0863698,19b5f2b3,6ade9755,2318644b,fea54f57,gpt4_213fd887," +
            "gpt4_21adecb5,2b8f3739,8e9d538c,3c1045c8,gpt4_2655b836,0ddfec37,577d4d32,gpt4_7bc6cf22," +
            "af8d2e46,41698283,f0e564bc,a9f6b44c,4100d0a0,19b5f2b3_abs,e61a7584,e4e14d04," +
            "gpt4_d12ceb0e,1c0ddc50,18bc8abd"
        },
        {
            30, true, 7,
            "0862e8bf,36580ce8,19b5f2b3,6ade9755,e3038f8c,720133ac,aae3761f,2311e44b_abs,157a136e," +
            "a3332713,2311e44b,e56a43b9,09d032c9,35a27287,6613b389,gpt4_e061b84g,d01c6aa8," +
            "gpt4_a2d1d1f6,b29f3365,gpt4_b5700ca9,dcfa8644,08f4fc43,031748ae,8fb83627,18bc8abd," +
            "d7c942c3,0ddfec37_abs,c4f10528,1568498a,5809eb10"
        },
        {
            10, true, 42,
            "19b5f2b3,gpt4_15e38248,2e6d26dc,d24813b1,gpt4_7abb270c,8077ef71,gpt4_483dd43c,0e4e4c46," +
            "4d6b87c8,4388e9dd"
        }
    };

    [Theory]
    [MemberData(nameof(V019GoldenSelections))]
    public void DefaultOptions_DrawExactlyTheSampleV019Drew(
        int maxQuestions, bool stratified, int seed, string expectedIds)
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = maxQuestions,
            StratifiedSampling = stratified,
            RandomSeed = seed
        });

        Assert.Equal(expectedIds, string.Join(",", selected.Select(e => e.QuestionId)));
    }

    /// <summary>
    /// The shipped Subset preset draws no abstention question at all. Pinned because it is not
    /// visible in any configuration value: it is a property of one seed against one dataset.
    /// </summary>
    [Fact]
    public void SubsetPreset_DrawsZeroAbstentionQuestions()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = LongMemEvalBenchmark.SubsetMaxQuestions,
            StratifiedSampling = true,
            RandomSeed = 42
        });

        Assert.Equal(50, selected.Count);
        Assert.DoesNotContain(selected, e => e.IsAbstention);
        // And repeating the run does not widen coverage — a fixed seed re-draws the same questions,
        // so N runs measure one sample N times.
        var again = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = LongMemEvalBenchmark.SubsetMaxQuestions,
            StratifiedSampling = true,
            RandomSeed = 42
        });
        Assert.Equal(selected.Select(e => e.QuestionId), again.Select(e => e.QuestionId));
    }

    // ── Ask 1 proof: a requested type returns only that type ──────────────────

    [Fact]
    public void IncludeQuestionTypes_ReturnsOnlyTheRequestedTypeAndHonoursTheCount()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 30,
            IncludeQuestionTypes = [SingleSessionAssistant],
            RandomSeed = 42
        });

        // "30 single-session-assistant questions", not "50 of which 6 are".
        Assert.Equal(30, selected.Count);
        Assert.All(selected, e => Assert.Equal(SingleSessionAssistant, e.QuestionType));
    }

    [Fact]
    public void IncludeQuestionTypes_WithoutTheFilter_TheSameBudgetYieldsOnlySixOfThatType()
    {
        // The problem the filter solves, measured rather than asserted.
        var unfiltered = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 50,
            StratifiedSampling = true,
            RandomSeed = 42
        });

        Assert.Equal(6, unfiltered.Count(e => e.QuestionType == SingleSessionAssistant));
    }

    [Fact]
    public void IncludeQuestionTypes_MultipleTypes_StratifiesWithinThem()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 40,
            StratifiedSampling = true,
            IncludeQuestionTypes = [SingleSessionAssistant, TemporalReasoning],
            RandomSeed = 42
        });

        Assert.Equal(40, selected.Count);
        Assert.All(selected, e => Assert.Contains(e.QuestionType, new[] { SingleSessionAssistant, TemporalReasoning }));
        // Both requested types are represented — stratification still applies inside the filter.
        Assert.Contains(selected, e => e.QuestionType == SingleSessionAssistant);
        Assert.Contains(selected, e => e.QuestionType == TemporalReasoning);
    }

    [Fact]
    public void IncludeQuestionTypes_SameSeedReproducesTheSameSet()
    {
        static ExternalBenchmarkOptions Options() => new()
        {
            MaxQuestions = 25,
            IncludeQuestionTypes = [TemporalReasoning],
            RandomSeed = 1234
        };

        var first = Load(Options()).Select(e => e.QuestionId).ToArray();
        var second = Load(Options()).Select(e => e.QuestionId).ToArray();

        Assert.Equal(first, second);
    }

    [Fact]
    public void IncludeQuestionTypes_DifferentSeedDrawsADifferentSet()
    {
        var first = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 25,
            IncludeQuestionTypes = [TemporalReasoning],
            RandomSeed = 1
        }).Select(e => e.QuestionId).ToArray();

        var second = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 25,
            IncludeQuestionTypes = [TemporalReasoning],
            RandomSeed = 2
        }).Select(e => e.QuestionId).ToArray();

        Assert.NotEqual(first, second);
    }

    public static TheoryData<string[]?> NoTypeFilter()
    {
        var data = new TheoryData<string[]?>();
        data.Add(null);
        data.Add(Array.Empty<string>());
        return data;
    }

    [Theory]
    [MemberData(nameof(NoTypeFilter))]
    public void IncludeQuestionTypes_NullOrEmpty_IsTodayExactly(string[]? types)
    {
        var filtered = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 50,
            StratifiedSampling = true,
            RandomSeed = 42,
            IncludeQuestionTypes = types
        });

        var baseline = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 50,
            StratifiedSampling = true,
            RandomSeed = 42
        });

        Assert.Equal(baseline.Select(e => e.QuestionId), filtered.Select(e => e.QuestionId));
    }

    [Fact]
    public void IncludeQuestionTypes_UnknownType_SelectsNothingRatherThanFallingBackToEverything()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 10,
            IncludeQuestionTypes = ["no-such-type"],
            RandomSeed = 42
        });

        // A typo must not quietly return a full-spectrum sample that then gets reported as per-type.
        Assert.Empty(selected);
    }

    // ── Ask 2 proof: abstention excluded / included / targeted ────────────────

    [Fact]
    public void AbstentionPolicy_Exclude_RemovesEveryAbstentionQuestion()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 50,
            AbstentionPolicy = AbstentionSamplingPolicy.Exclude,
            RandomSeed = 42
        });

        Assert.Equal(50, selected.Count);
        Assert.DoesNotContain(selected, e => e.IsAbstention);
    }

    [Fact]
    public void AbstentionPolicy_Only_SelectsAbstentionQuestionsExclusively()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 20,
            AbstentionPolicy = AbstentionSamplingPolicy.Only,
            RandomSeed = 42
        });

        Assert.Equal(20, selected.Count);
        Assert.All(selected, e => Assert.True(e.IsAbstention));
    }

    [Fact]
    public void AbstentionPolicy_Only_WithNoBudget_ReturnsAllThirty()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            AbstentionPolicy = AbstentionSamplingPolicy.Only
        });

        Assert.Equal(30, selected.Count);
        Assert.All(selected, e => Assert.True(e.IsAbstention));
    }

    [Theory]
    [InlineData(20, 0.5, 10, 10)]
    [InlineData(20, 0.25, 5, 15)]
    [InlineData(40, 0.1, 4, 36)]
    public void AbstentionPolicy_TargetProportion_SplitsTheBudgetAsRequested(
        int maxQuestions, double proportion, int expectedAbstention, int expectedOrdinary)
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = maxQuestions,
            AbstentionPolicy = AbstentionSamplingPolicy.TargetProportion,
            AbstentionTargetProportion = proportion,
            RandomSeed = 42
        });

        Assert.Equal(expectedAbstention, selected.Count(e => e.IsAbstention));
        Assert.Equal(expectedOrdinary, selected.Count(e => !e.IsAbstention));
    }

    [Fact]
    public void AbstentionPolicy_TargetProportion_ShortPool_IsLeftShortNotToppedUp()
    {
        // 80% of 100 is 80 abstention questions; only 30 exist. Topping up from the ordinary pool
        // would return a full 100 that quietly measured something else.
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 100,
            AbstentionPolicy = AbstentionSamplingPolicy.TargetProportion,
            AbstentionTargetProportion = 0.8,
            RandomSeed = 42
        });

        Assert.Equal(30, selected.Count(e => e.IsAbstention));
        Assert.Equal(20, selected.Count(e => !e.IsAbstention));
        Assert.Equal(50, selected.Count);
    }

    [Fact]
    public void AbstentionPolicy_ComposesWithTypeFilter()
    {
        var selected = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 20,
            IncludeQuestionTypes = [TemporalReasoning],
            AbstentionPolicy = AbstentionSamplingPolicy.Only,
            RandomSeed = 42
        });

        // temporal-reasoning holds 6 abstention questions, so the budget cannot be filled.
        Assert.Equal(6, selected.Count);
        Assert.All(selected, e =>
        {
            Assert.True(e.IsAbstention);
            Assert.Equal(TemporalReasoning, e.QuestionType);
        });
    }

    [Fact]
    public void AbstentionPolicy_AsSampled_IsTodayExactly()
    {
        var explicitPolicy = Load(new ExternalBenchmarkOptions
        {
            MaxQuestions = 50,
            RandomSeed = 42,
            AbstentionPolicy = AbstentionSamplingPolicy.AsSampled
        });

        var baseline = Load(new ExternalBenchmarkOptions { MaxQuestions = 50, RandomSeed = 42 });

        Assert.Equal(baseline.Select(e => e.QuestionId), explicitPolicy.Select(e => e.QuestionId));
    }

    // ── Validation: no silently-ignored configuration ─────────────────────────

    [Fact]
    public void Validate_TargetProportionWithoutAProportion_Throws()
    {
        var options = new ExternalBenchmarkOptions
        {
            AbstentionPolicy = AbstentionSamplingPolicy.TargetProportion
        };

        Assert.Throws<ArgumentException>(options.Validate);
    }

    [Fact]
    public void Validate_ProportionWithoutTheMatchingPolicy_Throws()
    {
        // Would otherwise look configured for a 30% abstention share and apply none of it.
        var options = new ExternalBenchmarkOptions
        {
            AbstentionPolicy = AbstentionSamplingPolicy.Exclude,
            AbstentionTargetProportion = 0.3
        };

        Assert.Throws<ArgumentException>(options.Validate);
    }

    [Theory]
    [InlineData(-0.1)]
    [InlineData(1.5)]
    [InlineData(double.NaN)]
    public void Validate_ProportionOutOfRange_Throws(double proportion)
    {
        var options = new ExternalBenchmarkOptions
        {
            AbstentionPolicy = AbstentionSamplingPolicy.TargetProportion,
            AbstentionTargetProportion = proportion
        };

        Assert.Throws<ArgumentOutOfRangeException>(options.Validate);
    }

    [Fact]
    public void Validate_BlankQuestionType_Throws()
    {
        var options = new ExternalBenchmarkOptions { IncludeQuestionTypes = ["  "] };

        Assert.Throws<ArgumentException>(options.Validate);
    }

    [Fact]
    public void Validate_DefaultOptions_Pass()
    {
        new ExternalBenchmarkOptions().Validate();
    }
}
